sudo: required

services:
  - docker

language: go
go:
  - 1.9

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3 python3-pip python3-setuptools
  - python3 -m pip install --user pip setuptools wheel twine

before_script:
  - export RANDOM=$(date | md5sum | head -c 4)
  - sed -i s/0.1.0/0.2.9${RANDOM}/g testdata/setup.py

script:
  - go vet
  - go test -cover -coverprofile=coverage.out
  - rm -rf dist
  - rm -rf drone_pypi_test.egg-info
  - |
    if test "${TRAVIS_TAG}" = ""; then
      go build -ldflags "-X main.build=${TRAVIS_BUILD_NUMBER}" -a -o release/linux/amd64/drone-pypi
    else
      go build -v -ldflags "-X main.version=${TRAVIS_TAG##v} -X main.build=${DRONE_BUILD_NUMBER}" -a -o release/linux/amd64/drone-pypi
    fi

after_success:
  - docker login --username $DOCKER_USER --password-stdin <<< $DOCKER_PASS
  - docker build -t $DOCKER_USER/$DOCKER_REPO:build --build-arg GITSHA=$TRAVIS_COMMIT --build-arg BUILDDATE="`date`" .
  - |
    if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker tag $DOCKER_USER/$DOCKER_REPO:build $DOCKER_USER/$DOCKER_REPO:latest
    else
      docker tag $DOCKER_USER/$DOCKER_REPO:build $DOCKER_USER/$DOCKER_REPO:${TRAVIS_BRANCH##v};
    fi
  - docker rmi $DOCKER_USER/$DOCKER_REPO:build
  - docker push $DOCKER_USER/$DOCKER_REPO

env:
  global:
  - PLUGIN_REPOSITORY=https://test.pypi.org/legacy/
  - PLUGIN_DISTRIBUTIONS=sdist
  - DOCKER_REPO=drone-pypi
